# Configura a base de dados para usar as variáveis de ambiente que o Render vai fornecer
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Diz ao Hibernate para usar o dialeto do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Esta linha é importante: o Hibernate vai atualizar a estrutura da base de dados
# automaticamente com base nas suas entidades (@Entity).
spring.jpa.hibernate.ddl-auto=update
